# Generated by Django 3.1.12 on 2021-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
