# Generated by Django 3.1.12 on 2021-11-10 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_food_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='store.restaurant'),
        ),
    ]
