# Generated by Django 3.1.12 on 2021-11-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211110_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testUser',
        ),
    ]
